<img style='float: right; height:85%; width: 25%' src="https://raw.githubusercontent.com/calixtops/ES/main/img/logo_OEPY.png" >


<h1 style="text-align: center"> Aula 2 - Estrutura de Dados em Python </h1>
<a id='section_id1'></a>


---

# Índice

[**Aula 2 - Estrutura de Dados em Python**](#section_id1)
- [1. Tuplas](#section_id2)
    - [1.1 Operadores Relacionais](#section_id3)
    - [1.2 Teste de Pertinência](#section_id4)
    - [1.3 Criando Funções](#section_id5)
- [2. Cadeias de Caracteres (Strings)](#section_id6)
    - [2.1 Conversão Entre Tipos](#section_id7)

- [3. Listas](#section_id8)
    - [3.1 Fatiamento de Listas](#section_id9)
    - [3.2 Métodos Utilizados em Listas](#section_id10)

- [4. Dicionários](#section_id11)
- [5. Numpy Array](#section_id12)


<p style="text-decoration: underline">Estutura de dados é qualquer meio utilizado para armazenar ou recuperar informações</p>


Abordaremos nessa aula as estruturas de dados como:
Tuplas, cadeias de caracteres (string), listas, arquivos e dicionários.

## 1. Tuplas
<a id='section_id2'></a>



<div class="alert alert-block alert-success">


<b>Uma tupla é um sequência de valores distintos de acordo com a posição
em que aparecem na tupla. Em uma tupla, os valores componentes sao separados
por vírgula.<b>
    </div>

In [1]:
dupla = 'abc',10

In [2]:
print(dupla)

('abc', 10)


In [3]:
tripla = 1,True,'1'

In [4]:
tripla

(1, True, '1')

<mark style="background-color:red">Aqui nos deparamos com um novo tipo de valor, o tipo "Boolean" ou Booleano.</mark>
    
<b> Em Python, uma variável pode assumir valor booleano True (verdadeiro) ou False (falso). Esses valores são úteis para representar, por exemplo, o resultado de uma comparação. Experimente: <b>

In [5]:
a = 3

In [6]:
b = 4

In [7]:
c = a < b # c recebe o valor da comparação a < b

In [8]:
print(c)

True


In [9]:
type(c)

bool

Uma aplicação para os valores booleanos é a utilização de Operadores Relacionais e Operadores Comparativos.

### 1.1 Operadores Relacionais
<a id='section_id3'></a>


<div class="alert alert-block alert-success">


<b>Operador Relacional ou Comparativo é todo operador que obtém a relação do membro a esquerda com o membro a sua direita. São símbolos utilizados para fazer comparações.
    </div>

<img src="https://aprendendoprogramacaocombr.files.wordpress.com/2018/08/relacionais.jpg?w=723" width=600px height=600px/>


Algumas formas de fazer comparações em python

In [10]:
d = a > b # d recebe o valor da comparação a > b

In [11]:
print(d)

False


In [12]:
e = a == b # e recebe o valor da comparação a == b

In [13]:
e

False

In [14]:
print("Valor de c: {} ".format(c))
print("Valor de d: {} ".format(d))
print("Valor de e: {} ".format(e))


Valor de c: True 
Valor de d: False 
Valor de e: False 


<div class="alert alert-block alert-info">

<b> Expressões aritméticas, como 2 + 3 * 4, são formadas por valores e operadores aritméticos +, *, -, /.
    
De maneira semelhante, expressões lógicas ou booleanas são formadas por valores e os operadores lógicos tais como and, or e not.
    </div>

Dado dois valores booleanos A e B, o operador lógico **and** resulta em **True** apenas quando A e B foram ambos **True**, e retorna **False** caso contrário.

In [15]:
A = True
B = False
print("Valor de A e B: ", A and B)

Valor de A e B:  False


O conector **and** significa que as duas condições devem ser verdadeiras. 

**Exemplo:** Ao finalizar o curso, alunos de uma certa disciplina devem possuir nota maior que 7 e devem possuir, no máximo, 10 faltas. Para aferir essas condição temos a seguinte relação.

In [16]:
nota = 7 
faltas = 9

In [17]:
nota >=7 and faltas <=10

True

O valor de saída <b>True</b> quer dizer que a condição para que o aluno passe de ano foi satisfeita.

### 1.2 Teste de Pertinência

<a id='section_id4'></a>


<p><code class="docutils literal notranslate"><span class="pre">in</span></code> e <code class="docutils literal notranslate"><span class="pre">not</span> <span class="pre">in</span></code> são operadores booleanos ou lógicos que testam a pertinência
 em uma sequência.</p>

In [18]:
dupla = 'abc',10

In [19]:
cadeia = 'Hoje eu acordei e li um livro legal.'

In [20]:
10 in dupla

True

In [21]:
'livro  ' in cadeia

False

In [22]:
'livro  ' not in cadeia

True

In [23]:
'livro' in cadeia

True

In [24]:
print(dupla[0])

abc


In [25]:
print(dupla[1])

10


In [26]:
dupla[-2]

'abc'

In [27]:
tripla

(1, True, '1')

### 1.3 Criando Funções
<a id='section_id5'></a>


<p>Até aqui, temos utilizado somente as funções internas do Python, mas também é possível adicionar novas funções. Criar novas funções para resolver seus próprios problemas é uma das coisas mais úteis de uma linguagem de programação de propósito geral.</p>

<div class="alert alert-block alert-success">


<strong>Função</strong> é uma sequência nomeada de instruções ou comandos, que realizam uma operação desejada. Esta operação é especificada na <strong>definição da função</strong>. 
    </div>

<p>A sintaxe para definir uma função é:</p>

<div style="background-color: gray">
<img src="https://raw.githubusercontent.com/calixtops/ES/main/img/Screenshot%20from%202021-04-05%2018-13-18.png" />
</div>

Você pode usar o nome que quiser para as funções que deseja criar, exceto as palavras reservadas do Python. 

A lista de argumentos especifíca quais argumentos ou parâmetros, se houver, você tem que fornecer para poder usar a nova função.

Uma função pode ter quantos comandos forem necessários, mas eles precisam estar identados a partir da margem esquerda.

As primeiras funções que vamos mostrar não terão argumentos, então, a sintaxe terá a seguinte aparência:

In [28]:
def novaLinha():
  ''' Help para a função novalinha()
  Essa função adiciona uma linha'''
  print()

In [29]:
novaLinha?

Esta função é chamada de <code class="docutils literal"><span class="pre">novaLinha</span></code>. Os parênteses vazios indicam que ela não tem parâmetros. Contém apenas um único comando, que gera como saída um caractere de nova linha (isso é o que acontece quando você usa um comando <code class="docutils literal"><span class="pre">print</span></code> sem qualquer argumento).</p>

<p>A sintaxe para executar a nossa nova função é a mesma sintaxe para as funções nativas:</p>

In [30]:
print( 'Primeira Linha.')
novaLinha()
print( 'Segunda Linha.')

Primeira Linha.

Segunda Linha.


Observe o espaço extra entre as duas linhas. E se desejarmos mais espaço entre as linhas? Poderíamos chamar a mesma função repetidamente:

In [31]:
print( 'Primeira Linha.')
novaLinha()
novaLinha()
novaLinha()
print( 'Segunda Linha.')

Primeira Linha.



Segunda Linha.


Ou poderíamos escrever uma nova função chamada <code class="docutils literal"><span class="pre">tresLinhas</span></code>, que produzisse três novas linhas:

In [32]:
def tresLinhas() :
  novaLinha()
  novaLinha()
  novaLinha()

print( 'Primeira Linha.')
tresLinhas()
print( 'Segunda Linha.')

Primeira Linha.



Segunda Linha.


<p>Esta função contém três comandos, todos com recuo de dois espaços a partir da margem esquerda. Já que o próximo comando não está identado, o Python reconhece que ele não faz parte da função.</p>


#### Criando uma função com operadores aritméticos 

Utilizando os conceitos da Aula 1, podemos montar funções que utilizem o que aprendemos.

In [33]:
def soma(a,b):
    c = a + b
    print('a soma da variavel a + b é igual a {}'.format(c))

**Note que agora temos ARGUMENTOS ou PARAMETROS na função que criamos.**

In [34]:
soma(6,7)

a soma da variavel a + b é igual a 13


A função <mark>return</mark> serve para retornar algum valor ou variável de uma função, ou simplesmente encerrar a função.

In [35]:
def soma(a,b):
    print('a soma da variavel a + b é igual a {}'.format(a+b))
    return a+b

In [36]:
c = soma(5,3)
print(c)

a soma da variavel a + b é igual a 8
8


## 2. Cadeias de Caracteres (Strings)
<a id='section_id6'></a>

<div class="alert alert-block alert-success">

Caractere é a únidade mínima de toda String. Um caractere pode ser numérico, letras do alfabeto ou um caractere especial. Para o Python, tudo são Strings, indiferente se a mesma contiver 1 ou "n" caracteres.
    </div>

In [37]:
type("Olá")

str

In [38]:
type('O')

str

Uma das formas usais de manipular Strings e outros valores é **CONCATENANDO**.

**Concatenar é, basicamente, juntar 2 cadeias de caracteres dando origem a uma nova string.**

In [39]:
concatenado = "Ola, " + "mundo"

In [40]:
print(concatenado)

Ola, mundo


Podemos utilizar a indexação para acessar elementos dentro de cadeias de caracteres:

In [41]:
concatenado[1]

'l'

In [42]:
tupla = concatenado[0], concatenado[1], concatenado[2]

In [43]:
tupla

('O', 'l', 'a')

In [44]:
tupla[0] + tupla[1] + tupla[2]

'Ola'

In [45]:
tupla[0:3]

('O', 'l', 'a')

Podemos usar intervalos maiores para selecionar elementos dentro da cadeia. **Indexação**

In [46]:
concatenado[0:10:2]

'Oa ud'

<div class="alert alert-block alert-info">


A **indexação** é utilizada para acessar um ou vários elementos da nossa cadeia.

x[i] retorna o elemento na i-ésima posição da cadeia. O indice **i** deve ser um numero inteiro.

O indice **i** também pode ser negativo.
    </div>

In [47]:
concatenado[-1]

'o'

In [48]:
concatenado[-2]

'd'

<div class="alert alert-block alert-info">


Teste de existencia de sub-cadeia

d **in** c retorna **True** se d é uma sub-cadeia de c

d **not in** c retorna **True** se d não é uma subcadeia de c
    </div>

In [49]:
"cd" in "abcde"

True

In [50]:
"ce" in "abcde"


False

In [51]:
"ce" not in "abcde" 

True

### 2.1 Conversão entre tipos
<a id='section_id7'></a>


O Python provê uma coleção de funções nativas que convertem valores de um tipo em outro. A função **int** recebe um valor e o converte para inteiro, se possível.

In [52]:
int('32')

32

In [53]:
type(int('32'))

int

A função **int** também pode converter valores em ponto flutuante para inteiro, mas lembre que isso trunca a parte fracionária:

In [54]:
int(3.999999)

3

In [55]:
import numpy as np

In [56]:
int(-2.3)

-2

A função "float" converte inteiros e strings em números do tipo ponto flutuante:



In [57]:
float(2)

2.0

In [58]:
float('2')

2.0

## 3. Listas
<a id='section_id8'></a>


<div class="alert alert-block alert-success">


Uma **lista(<i>list</i>)** em Python é uma sequência ou coleção ordenada de valores. Listas são semelhantes às tuplas, podendo conter elementos de tipos distintos, porém, usualmente os elementos de listas são formados por elementos do mesmo tipo. 

A diferença principal entre listas e tuplas é que listas são mutáveis, enquanto tuplas são imutaveis.
    </div>

In [59]:
lista = [1,2,3,4,5,6,7]

In [60]:
print(lista)

[1, 2, 3, 4, 5, 6, 7]


In [61]:
np.array(lista) * 2

array([ 2,  4,  6,  8, 10, 12, 14])

Os elementos na lista são escritos entre colchetes, separados também por virgulas.

### 3.1 Fatiamento de listas
<a id='section_id9'></a>


Muitas vezes, ao invés de considerar a lista completa, é necessário consider apenas um pedaço contínuo da lista, que podemos definir por 2 índices que marcam o início e o fim desse pedaço, que chamamos de fatia da lista.

In [62]:
lista[0:2]

[1, 2]

In [63]:
lista[1]

2

In [64]:
lista[2:5]

[3, 4, 5]

In [65]:
lista[:]

[1, 2, 3, 4, 5, 6, 7]

In [66]:
print('Os dois primeiros numeros da lista em questão são {} e {}'.format(lista[0],lista[1]))

Os dois primeiros numeros da lista em questão são 1 e 2


### 3.2 Métodos Utilizados em Listas
<a id='section_id10'></a>


O tipo de dado **lista**, possui diversos métodos. Abaixa você pode observar alguns métodos de objetos do tipo lista: 

<ul>
	<li>x.insert(i,e): insere 'e' na posição 'i' de x:
</ul>


In [67]:
x = [1,2,3]

In [68]:
x.insert(0,4)

In [69]:
x

[4, 1, 2, 3]

In [70]:
x.insert(0,5)

In [71]:
x.sort()
print(x)

[1, 2, 3, 4, 5]


<ul>
<li>x.pop(): remove e retorna o elemento de índice "i" de "x"; se usar x.pop() o último elemento de "x" será removido de x e retornado
</ul>


In [72]:
x = [1,2,3]

In [73]:
x.pop()


3

In [74]:
x

[1, 2]

In [75]:
x.pop(0)

1

In [76]:
x

[2]

<ul>
	<li>x.append(): insere 'e' no fim de x:
</ul>

In [77]:
x.append(4)

In [78]:
x

[2, 4]

<ul>
	<li>x.remove(e): remove a primeira ocorrência do elemento "e" em x:
</ul>

In [79]:
x = [1,2,3,1]

In [80]:
x.remove(1)

In [81]:
print(x)

[2, 3, 1]


<ul>
	<li>x.count(e): retorna o número de ocorrências de "e" em "x":
</ul>

In [82]:
x = [1,2,3,1]
x.count(1)


2

In [83]:
x.count(4)

0

<ul>
	<li>sorted(x),x.sort(): retorna x em ordem crescente:
</ul>


In [84]:
x = [4,2,3,1]

In [85]:
x.sort()

In [86]:
x

[1, 2, 3, 4]

<ul>
	<li>min(x),max(x): Retorna o menor (maior) elemento de x:
</ul>


In [87]:
x = [2,1,3]

In [88]:
min(x)

1

In [89]:
max(x)

3

<ul>
	<li>sum(x), x.sum(): soma dos valores de x:
</ul>


In [90]:
x = [1,2,3]

In [91]:
sum(x)

6

<ul>
	<li>len(x): números de elementos em "x":
</ul>


In [92]:
x = [1,2,3]

In [93]:
len(x)

3

## 4. Dicionários
<a id='section_id11'>


<div class="alert alert-block alert-success">


Um dicionário é uma estrutura de dados que mapeia valores de entrada, usualmente chamado de chaves, à valores de saída, onde cada chave corresponde a um único valor de saída. A criação de dicionários pode ser feita por meio de diversos modos, usando listas ou conjuntos, de pares que associam um primeiro componente que é o valor da chave a seu valor correspondente:
    </div>

In [94]:
lv = []
dv = {}

In [95]:
dicionario = {'a':1,'b':2,'c':3}

In [96]:
print(dicionario)

{'a': 1, 'b': 2, 'c': 3}


In [97]:
dicionario['a']

1

In [98]:
dados = {'nome':'Joao','Idade':22,'Curso': 'Oceanografia'}

In [99]:
dados

{'nome': 'Joao', 'Idade': 22, 'Curso': 'Oceanografia'}

Podemos usar indexação no dicionario formado usando as Chaves as quais foram atribuidos os dados

In [100]:
dados['Idade']

22

Outras formas de criar dicionarios

In [101]:
zip('abc',[1,2,3,4])

In [102]:
x = dict(zip('abcd',[1,2,3,4]))

In [103]:
x

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [104]:
lista = ['Nome','Idade','Curso']
dados = ['Joao',22,'Oceano']

In [105]:
zip(lista,dados)

In [106]:
dicionario = dict(zip(lista,dados))

In [107]:
dicionario

{'Nome': 'Joao', 'Idade': 22, 'Curso': 'Oceano'}

In [108]:
x2 = dict(a=1,b=2,c=3)

In [109]:
x2

{'a': 1, 'b': 2, 'c': 3}

Adicionando chaves e elementos no dicionário

In [110]:
dicionario.update({'CPF':123456})


In [111]:
dicionario


{'Nome': 'Joao', 'Idade': 22, 'Curso': 'Oceano', 'CPF': 123456}

In [112]:
dicionario['dadox'] = 2345678

In [113]:
print(dicionario)

{'Nome': 'Joao', 'Idade': 22, 'Curso': 'Oceano', 'CPF': 123456, 'dadox': 2345678}


In [114]:
dicionario['coisax'] = 'lalala'

In [115]:
dicionario

{'Nome': 'Joao',
 'Idade': 22,
 'Curso': 'Oceano',
 'CPF': 123456,
 'dadox': 2345678,
 'coisax': 'lalala'}

Acessando o conteudo do dicionario e suas chaves:

In [116]:
dicionario.items()

dict_items([('Nome', 'Joao'), ('Idade', 22), ('Curso', 'Oceano'), ('CPF', 123456), ('dadox', 2345678), ('coisax', 'lalala')])

In [117]:
dicionario.keys()

dict_keys(['Nome', 'Idade', 'Curso', 'CPF', 'dadox', 'coisax'])

In [118]:
dicionario.values()

dict_values(['Joao', 22, 'Oceano', 123456, 2345678, 'lalala'])

## Numpy Array
<a id='section_id12'>


<div class="alert alert-block alert-success">

Numpy é a biblioteca central para computação científica em Python. Ele fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes. Se você já está familiarizado com o MATLAB, você pode achar este tutorial útil para começar a usar o Numpy.
    </div>

<div class="alert alert-block alert-success">

Uma matriz numpy é uma grade de valores, todos do mesmo tipo e é indexada por uma tupla de inteiros não negativos. O número de dimensões é a classificação da matriz; a forma de uma matriz é uma tupla de inteiros que fornece o tamanho da matriz ao longo de cada dimensão.
    </div>

Podemos criar uma array a partir de listas e também acessar cada elemento a partir da indexação;

In [119]:
import numpy as np 

In [120]:
a = np.array([1, 2, 3])   # Cria um numpy-array com 1 dimensão

In [121]:
a

array([1, 2, 3])

Algums métodos prórpios de um array podem ser de grande ajuda na manipulação dos seus dados.

In [122]:
a.shape

(3,)

In [123]:
a[0] = 5

In [124]:
a

array([5, 2, 3])

Podemos criar arrays e matrizes das seguintes formas:

**np.zeros(i,j)** $\rightarrow$ Cria um array com "shape/dimensão" pré definidas preenchidas com 0

In [125]:
a = np.zeros((2,2))   
print(a)          

[[0. 0.]
 [0. 0.]]


**np.ones(i,j)** $\rightarrow$ Cria um array com "shape/dimensão" pré definidas preenchidas com 1

In [126]:
b = np.ones((1,2))   
print(b)              

[[1. 1.]]


**np.full** $\rightarrow$ Cria um array com "shape/dimensão" pré definidas preenchidas com um numero a sua escolha 

In [127]:
c = np.full((2,2), np.nan) 
print(c)             

[[nan nan]
 [nan nan]]


In [128]:
cc = c = np.full((2,2), 1000) 
print(c)            

[[1000 1000]
 [1000 1000]]


**np.full** $\rightarrow$ Cria uma matrix identidade 

In [129]:
d = np.eye(2)  
print(d)              

[[1. 0.]
 [0. 1.]]


**np.full** $\rightarrow$ Cria um array com "shape/dimensão" pré definidas preenchidas com valores randomicos;

In [130]:
e = np.random.random((2,2)) 
print(e)

[[0.53330795 0.73112634]
 [0.71683206 0.41895441]]


<h3> As funções sum, mean, min e max;

Funções do Numpy utilizadas para operações básicas.

In [131]:
e.sum()

2.4002207584008817

In [132]:
e.mean()

0.6000551896002204

In [133]:
e.min()

0.41895440533938166

In [134]:
e.max()

0.731126340779177

------------------------------

<img src="https://raw.githubusercontent.com/calixtops/ES/main/img/logo_OEPY.png" style=" width: 150px; height:60px; align:center">